# Generated by Django 3.1 on 2020-12-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20201127_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
