# Generated by Django 3.1 on 2020-12-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201225_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postReactions', to='post.post'),
        ),
    ]
