# Generated by Django 3.1 on 2021-01-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20201230_2124'),
        ('post', '0010_auto_20210105_1930'),
    ]

    operations = [
    ]
