# Generated by Django 3.1 on 2020-12-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201225_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
