# Generated by Django 3.1 on 2021-01-05 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201225_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
