# Generated by Django 3.1 on 2021-01-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201225_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='endDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='startDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userschool',
            name='endYear',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userschool',
            name='startYear',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
