# Generated by Django 3.1 on 2021-01-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210106_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='detail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
