# Generated by Django 3.1 on 2021-01-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='media/test.png', upload_to='%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
