# Generated by Django 3.1 on 2021-01-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210105_1932'),
        ('user', '0007_userprofile_image'),
    ]

    operations = [
    ]
