# Generated by Django 3.1 on 2021-01-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_merge_20210108_2210'),
        ('user', '0007_userprofile_image'),
    ]

    operations = [
    ]
