# Generated by Django 3.1 on 2021-01-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210108_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_created',
            field=models.BooleanField(default=False),
        ),
    ]
