# Generated by Django 3.1 on 2021-01-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210108_2344'),
        ('user', '0010_userprofile_profile_created'),
    ]

    operations = [
    ]
